---
title: "Figure 3"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
### R Notebook to produce Figure 3 from the paper: 
### DOI: 
### Illustration of statistical signfigiant effects of stimulus valence x arousal on various HRV metrics
### Nanna Kildalh Mathiasen, Sebastian Scott Engen, Micah Allen
###
### 2020

rm(list=ls())
require(pacman)
```

Setup
```{r}
# WARNING: PACMAN WILL AUTOINSTALL NEEDED PACKAGES - USE AT YOUR OWN RISK! 
# Otherwise, just manually install these packages. 
pacman::p_load("plyr", "tidyr", "lattice", "ggplot2", "dplyr", "patchwork", "afex", "emmeans", "ggpol", "psychReport", "knitr",
              "cowplot","readr", "rmarkdown","Rmisc","devtools","gghalves","plotrix", "here")


```

Read in the data. 

```{r}

# set an automatic directory

abs_dic <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(abs_dic)
data_dir <- file.path(dirname(abs_dic), "Data/Preprocessed/")
figure_dir <- file.path(dirname(abs_dic), "Figures/")

# read the summary behavioral data
data <- read.csv(file.path(data_dir, "behaviour.txt"))


# set some labels
data$Valence <- factor(data$Valence, levels = c("Low", "High"))
data$Valence <- revalue(data$Valence, c("Low"="Negative", "High"="Positive"))
data$Arousal <- factor(data$Arousal, levels = c("Low", "High"))

data$xj <- jitter(as.numeric(as.factor(data$Arousal)), amount=0.05)

data$Arousal <- as.numeric(as.factor(data$Arousal))

summary_data <- data %>%
  group_by(Valence, Arousal) %>%
  select(-Subject, -X) %>%
  filter(Reject == 0) %>% # rejections determined by boxplot analysis, see prereg
  summarise_all(funs(mean, std.error))

head(summary_data)
```



Set general plot aesthetics

```{r}

# width and height variables for saved plots
w = 6
h = 4

# nudge variables for rainclouds
nudge_dot_a = -.16
nudge_dot_b = .16
nudge_cloud_a = -.26
nudge_cloud_b = .26
pd <- position_dodge(width = 0.05)

# colors
color_1 = "#00436A"
color_2 = "#FD6161"

# Sizes
line_summary_size = 1.5

```



Subpanel plots - Accuracy 
```{r Accuracy}
P_A <- ggplot(data = summary_data, aes(y = Accuracy_mean)) +

  # geoms for raw data
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = Accuracy),
                position = position_nudge(nudge_dot_a), alpha =.6, size=1)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = Accuracy),
                position = position_nudge(nudge_dot_b), alpha =.6,size=1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal,fill = Valence,y = Accuracy), position = position_nudge(x = nudge_cloud_a), 
     side = "l", alpha = .6, color = "black") +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal,fill = Valence,y = Accuracy), position = position_nudge(x = nudge_cloud_b), 
     side = "r", alpha = .6, color = "black") +
  
  # geoms for summary data
  geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = Accuracy_mean), position = pd, alpha = .6, size = line_summary_size) +
  
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = Accuracy_mean-Accuracy_std.error, ymax = Accuracy_mean+Accuracy_std.error),width = 0, size = line_summary_size, position = pd, alpha = 0.6) +
  
  geom_line(aes(x = Arousal, color=Valence,y = Accuracy_mean),  alpha = .6, size =  line_summary_size, position = pd) +
  
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0.6, 0.9))+
   
  #Define additional settings
  xlab("Arousal") + ylab("Accuracy") +
  ggtitle('D') +
  theme_cowplot()+
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c(color_1,color_2)) +
  scale_color_manual(values=c(color_1,color_2)) 
  
# uncomment if you want to save subplots seperately
#ggsave(filename="figures/Figure3_ACP_A.svg", plot=P_A, width = w, height = h,dpi=600)
#ggsave(filename="figures/Figure3_ACP_A.jpeg", plot=P_A, width = w, height = h,dpi=600)


P_A

```


Criterion

```{r Plotting B}

P_B <- ggplot(data = summary_data, aes(y = Criterion_mean)) +

  # geoms for raw data
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = Criterion),
                position = position_nudge(nudge_dot_a), alpha =.6, size=1)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = Criterion),
                position = position_nudge(nudge_dot_b), alpha =.6,size=1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal,fill = Valence,y = Criterion), position = position_nudge(x = nudge_cloud_a), 
     side = "l", alpha = .6, color = "black") +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal,fill = Valence,y = Criterion), position = position_nudge(x = nudge_cloud_b), 
     side = "r", alpha = .6, color = "black") +
  
  # geoms for summary data
  geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = Criterion_mean), position = pd, alpha = .6, size = line_summary_size) +
  
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = Criterion_mean-Criterion_std.error, ymax = Criterion_mean+Criterion_std.error),width = 0, size = line_summary_size, position = pd, alpha = 0.6) +
  
  geom_line(aes(x = Arousal, color=Valence,y = Criterion_mean),  alpha = .6, size =  line_summary_size, position = pd) +
  
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
   
  #Define additional settings
  xlab("Arousal") + ylab("Criterion") +
  ggtitle('D') +
  theme_cowplot()+
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c(color_1,color_2)) +
  scale_color_manual(values=c(color_1,color_2)) 

#ggsave(filename="figures/Figure3_CRP_B.svg", plot=P_B, width = w, height = h,dpi=600)
#ggsave(filename="figures/Figure3_CRP_B.jpeg", plot=P_B, width = w, height = h,dpi=600)


P_B
```

Reaction Time


```{r Plotting C}

P_C <- ggplot(data = summary_data, aes(y = RT_mean)) +

  # geoms for raw data
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = RT),
                position = position_nudge(nudge_dot_a), alpha =.6, size=1)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = RT),
                position = position_nudge(nudge_dot_b), alpha =.6,size=1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal,fill = Valence,y = RT), position = position_nudge(x = nudge_cloud_a), 
     side = "l", alpha = .6, color = "black") +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal,fill = Valence,y = RT), position = position_nudge(x = nudge_cloud_b), 
     side = "r", alpha = .6, color = "black") +
  
  # geoms for summary data
  geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = RT_mean), position = pd, alpha = .6, size = line_summary_size) +
  
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = RT_mean-RT_std.error, ymax = RT_mean+RT_std.error),width = 0, size = line_summary_size, position = pd, alpha = 0.6) +
  
  geom_line(aes(x = Arousal, color=Valence,y = RT_mean),  alpha = .6, size =  line_summary_size, position = pd) +
  
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
   
  #Define additional settings
  xlab("Arousal") + ylab("Reaction Time (s)") +
  ggtitle('D') +
  theme_cowplot()+
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c(color_1,color_2)) +
  scale_color_manual(values=c(color_1,color_2)) 

#ggsave(filename="figures/Figure3_RTP_C.svg", plot=P_C, width = w, height = h,dpi=600)
#ggsave(filename="figures/Figure3_RTP_C.jpeg", plot=P_C, width = w, height = h,dpi=600)


P_C

```

Confidence
```{r Plotting D}

P_D <- ggplot(data = summary_data, aes(y = Confidence_mean)) +

  # geoms for raw data
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = Confidence),
                position = position_nudge(nudge_dot_a), alpha =.6, size=1)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = Confidence),
                position = position_nudge(nudge_dot_b), alpha =.6,size=1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal,fill = Valence,y = Confidence), position = position_nudge(x = nudge_cloud_a), 
     side = "l", alpha = .6, color = "black") +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal,fill = Valence,y = Confidence), position = position_nudge(x = nudge_cloud_b), 
     side = "r", alpha = .6, color = "black") +
  
  # geoms for summary data
  geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = Confidence_mean), position = pd, alpha = .6, size = line_summary_size) +
  
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = Confidence_mean-Confidence_std.error, ymax = Confidence_mean+Confidence_std.error),width = 0, size = line_summary_size, position = pd, alpha = 0.6) +
  
  geom_line(aes(x = Arousal, color=Valence,y = Confidence_mean),  alpha = .6, size =  line_summary_size, position = pd) +
  
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
  scale_y_continuous(limits=c(2,6), breaks = seq(2,6, by = 1))+ 
  #Define additional settings
  xlab("Arousal") + ylab("Confidence") +
  ggtitle('D') +
  theme_cowplot()+
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c(color_1,color_2)) +
  scale_color_manual(values=c(color_1,color_2))

#ggsave(filename="figures/Figure3_CP_D.svg", plot=P_D, width = w, height = h,dpi=600)
#ggsave(filename="figures/Figure3_CP_D.jpeg", plot=P_D, width = w, height = h,dpi=600)

P_D

```


M-prime
```{r Plotting E}

P_E <- ggplot(data = summary_data, aes(y = MetadPrime_mean)) +

  # geoms for raw data
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = MetadPrime),
                position = position_nudge(nudge_dot_a), alpha =.6, size=1)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = MetadPrime),
                position = position_nudge(nudge_dot_b), alpha =.6,size=1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal,fill = Valence,y = MetadPrime), position = position_nudge(x = nudge_cloud_a), 
     side = "l", alpha = .6, color = "black") +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal,fill = Valence,y = MetadPrime), position = position_nudge(x = nudge_cloud_b), 
     side = "r", alpha = .6, color = "black") +
  
  # geoms for summary data
  geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = MetadPrime_mean), position = pd, alpha = .6, size = line_summary_size) +
  
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = MetadPrime_mean-MetadPrime_std.error, ymax = MetadPrime_mean+MetadPrime_std.error),width = 0, size = line_summary_size, position = pd, alpha = 0.6) +
  
  geom_line(aes(x = Arousal, color=Valence,y = MetadPrime_mean),  alpha = .6, size =  line_summary_size, position = pd) +
  
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
  scale_y_continuous(limits=c(0,3), breaks = seq(0,3, by = 1))+ 
  #Define additional settings
  xlab("Arousal") + ylab("MetadPrime") +
  ggtitle('D') +
  theme_cowplot()+
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c(color_1,color_2)) +
  scale_color_manual(values=c(color_1,color_2)) 

#ggsave(filename="figures/Figure3_MDP_E.svg", plot=P_E, width = w, height = h,dpi=600)
#ggsave(filename="figures/Figure3_MDP_E.jpeg", plot=P_E, width = w, height = h,dpi=600)

P_E

```

M-Ratio
```{r Plotting F}

P_F <- ggplot(data = summary_data, aes(y = Mratio_mean)) +

  # geoms for raw data
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = Mratio),
                position = position_nudge(nudge_dot_a), alpha =.6, size=1)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = Mratio),
                position = position_nudge(nudge_dot_b), alpha =.6,size=1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal,fill = Valence,y = Mratio), position = position_nudge(x = nudge_cloud_a), 
     side = "l", alpha = .6, color = "black") +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal,fill = Valence,y = Mratio), position = position_nudge(x = nudge_cloud_b), 
     side = "r", alpha = .6, color = "black") +
  
  # geoms for summary data
  geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = Mratio_mean), position = pd, alpha = .6, size = line_summary_size) +
  
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = Mratio_mean-Mratio_std.error, ymax = Mratio_mean+Mratio_std.error),width = 0, size = line_summary_size, position = pd, alpha = 0.6) +
  
  geom_line(aes(x = Arousal, color=Valence,y = Mratio_mean),  alpha = .6, size =  line_summary_size, position = pd) +
  
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
   
  #Define additional settings
  xlab("Arousal") + ylab("M-ratio") +
  ggtitle('D') +
  theme_cowplot()+
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c(color_1,color_2)) +
  scale_color_manual(values=c(color_1,color_2)) 

#ggsave(filename="figures/Figure3_MR_F.svg", plot=P_F, width = w, height = h,dpi=600)
#ggsave(filename="figures/Figure3_MR_F.jpeg", plot=P_F, width = w, height = h,dpi=600)

P_F

```

Assemble plots into overall figure. 
```{r}

fig3<- P_A + P_B + P_C + P_D + P_E + P_F + plot_layout(guides = 'collect', ncol = 3)#, heights = c(10,10), widths = c(10,10,10))


#ggsave(file.path(figure_dir, "Figure3.svg"), plot=fig3, width = 12, height = 6,dpi=600)
#ggsave(file.path(figure_dir, "Figure3.png"), plot=fig3, width = 12, height = 6,dpi=600)
#ggsave(file.path(figure_dir, "Figure3.jpeg"), plot=fig3, width = 12, height = 6,dpi=600)

fig3

```


Optional plot - dprime (sensitivity)


```{r Dprime}

P_dprime <- ggplot(data = summary_data, aes(y = dPrime_mean)) +

  # geoms for raw data
   geom_point(data = data %>% filter(Arousal==1), aes(x = xj, colour = Valence, y = dPrime),
                position = position_nudge(nudge_dot_a), alpha =.6, size=1)+
   geom_point(data = data %>% filter(Arousal==2), aes(x = xj, colour = Valence, y = dPrime),
                position = position_nudge(nudge_dot_b), alpha =.6,size=1) +
   geom_half_violin(
     data = data %>% filter(Arousal=="1"),aes(x = Arousal,fill = Valence,y = dPrime), position = position_nudge(x = nudge_cloud_a), 
     side = "l", alpha = .6, color = "black") +
   geom_half_violin(
     data = data %>% filter(Arousal=="2"),aes(x = Arousal,fill = Valence,y = dPrime), position = position_nudge(x = nudge_cloud_b), 
     side = "r", alpha = .6, color = "black") +
  
  # geoms for summary data
  geom_point(data = summary_data, aes( x = Arousal, color = Valence, y = dPrime_mean), position = pd, alpha = .6, size = line_summary_size) +
  
  geom_errorbar(data = summary_data, aes(x = as.numeric(Arousal), colour = Valence, ymin = dPrime_mean-dPrime_std.error, ymax = dPrime_mean+dPrime_std.error),width = 0, size = line_summary_size, position = pd, alpha = 0.6) +
  
  geom_line(aes(x = Arousal, color=Valence,y = dPrime_mean),  alpha = .6, size =  line_summary_size, position = pd) +
  
  scale_x_continuous(breaks=c(1,2), labels=c("Low", "High"), limits=c(0, 3)) +
   
  #Define additional settings
  xlab("Arousal") + ylab("dPrime") +
  ggtitle('D') +
  theme_cowplot()+
  theme(title = element_text(size=14, face="bold"),axis.text.x = element_text(face = "bold", size = 14),axis.text.y = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),axis.line = element_line(colour = "black"))+
  scale_fill_manual(values=c(color_1,color_2)) +
  scale_color_manual(values=c(color_1,color_2)) 

#ggsave(filename="figures/Figure3_dprime.svg", plot=P_dprime, width = w, height = h,dpi=600)
P_dprime
```
